name: Add Field Automation

on:
  issue_comment:
    types: [created]

jobs:
  add-diff-to-pr:
    if: contains(github.event.comment.body, '/propagate')
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit changes

    steps:
      - name: Get PR Details
        id: get-pr-info
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}

          # Fetch PR details using GitHub API
          PR_DATA=$(gh api repos/$REPO/pulls/$PR_NUMBER)

          # Extract base and head branch
          BASE_BRANCH=$(echo "$PR_DATA" | jq -r '.base.ref')
          PR_BRANCH=$(echo "$PR_DATA" | jq -r '.head.ref')

          echo "Base branch: $BASE_BRANCH"
          echo "PR branch: $PR_BRANCH"

          # Store as environment variables
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
          echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PR_BRANCH }}
          fetch-depth: 2

      - name: Generate Diff File
        run: |
          mkdir -p .auto
          git fetch origin $BASE_BRANCH --depth=1
          git diff origin/$BASE_BRANCH...$PR_BRANCH --numstat -- automation/schemas | cut -f3 > .auto/schema-files.txt
          for f in $(cat .auto/schema-files.txt)
          do
            file=$(basename $f)
            cp $f .auto/${file}.new
            git checkout origin/$BASE_BRANCH -- $f
            cp $f .auto/${file}.orig
          done
          git reset --hard

      - name: Commit and Push Diff File
        run: |
          cat .auto/schema-files.txt
          ls .auto/
          for f in $(ls .auto/*.orig)
          do
            echo "The content of $f"
            cat $f
          done

