name: Add Field Automation

on:
  issue_comment:
    types: [created]

jobs:
  add-diff-to-pr:
    if: contains(github.event.comment.body, '/propagate')
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit changes

    steps:
      - name: Get PR Details
        id: get-pr-info
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}

          # Fetch PR details using GitHub API
          PR_DATA=$(gh api repos/$REPO/pulls/$PR_NUMBER)

          # Extract base and head branch
          BASE_BRANCH=$(echo "$PR_DATA" | jq -r '.base.ref')
          PR_BRANCH=$(echo "$PR_DATA" | jq -r '.head.ref')

          echo "Base branch: $BASE_BRANCH"
          echo "PR branch: $PR_BRANCH"

          # Store as environment variables
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
          echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PR_BRANCH }}
          fetch-depth: 2


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pwd
          ls -l
          pip install -r automation/requirements.txt

      - name: Extract Schema changes
        run: |
          mkdir -p .auto
          git fetch origin $BASE_BRANCH
          git diff origin/$BASE_BRANCH...HEAD --numstat -- automation/schemas | cut -f3 > .auto/schema-files.txt
          for f in $(cat .auto/schema-files.txt)
          do
            file=$(basename $f)
            cp $f .auto/${file}.new
            git checkout origin/$BASE_BRANCH -- $f
            cp $f .auto/${file}.orig
            automation/scripts/schema_extract.py .auto/${file}.new .auto/${file}.orig .auto/${file}
          done
          git reset --hard

      - name: Propagate Column code
        run: |
          for f in $(cat .auto/schema-files.txt)
          do
            schema_file=.auto/$(basename $f)
            for col_file_spec in $(automation/scripts/list.py column_files $f)
            do
              automation/scripts/apply.py column_spec $col_file_spec ${schema_file}
            done
          done

      - name: Propagate Column transform
        run: |
          for f in $(cat .auto/schema-files.txt)
          do
            schema_file=.auto/$(basename $f)
            for col_trans_file in $(automation/scripts/list.py column_trans $f)
            do
              automation/scripts/apply.py column_trans $col_trans_file ${schema_file}
            done
          done

      - name: Propagate Fixture Data
        run: |
          for f in $(cat .auto/schema-files.txt)
          do
            schema_file=.auto/$(basename $f)
            for ci_data in $(automation/scripts/list.py fixtures $f)
            do
              automation/scripts/apply.py fixture $ci_data ${schema_file}
            done
          done

