name: Add Diff File to PR Branch

on:
  issue_comment:
    types: [created]

jobs:
  add-diff-to-pr:
    if: contains(github.event.comment.body, '/add-diff')
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit changes

    steps:
      - name: Get PR Details
        id: get-pr-info
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}

          set -e -x
          body="${{ github.event.comment.body }}"
          trimmed="${body#"${body%%[![:space:]]*}"}"
          rest="${trimmed#*[[:space:]]}"
          restrim="${rest#"${rest%%[![:space:]]*}"}"
          awspath="${restrim%%[[:space:]]*}"
          # Fetch PR details using GitHub API
          PR_DATA=$(gh api repos/$REPO/pulls/$PR_NUMBER)

          # Extract base and head branch
          BASE_BRANCH=$(echo "$PR_DATA" | jq -r '.base.ref')
          PR_BRANCH=$(echo "$PR_DATA" | jq -r '.head.ref')

          echo "Base branch: $BASE_BRANCH"
          echo "PR branch: $PR_BRANCH"
          echo "S3 Path: $awspath"

          # Store as environment variables
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
          echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV
          echo "S3_PATH=$awspath" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PR_BRANCH }}
          fetch-depth: 0

      - name: Generate Diff File
        run: |
          echo "S3PATH: $S3_PATH"
          git fetch origin $BASE_BRANCH
          git diff origin/$BASE_BRANCH...HEAD -- > pr-diff.txt
          cat pr-diff.txt

      - name: Commit and Push Diff File
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Add the diff file
          git add pr-diff.txt

          # Commit if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add PR diff file"
            git push origin $PR_BRANCH
          fi